### ISSUE TITLE
Crash to main menu when attempting to visualize ghost entities

### ISSUE THREAD

**Issue by GeorgeBroughton** [M10241024/Factorio-Circuit-Visualizer#1]
Happens consistently when placing this blueprint, not having the items to actually build it, hovering over the rightmost filtered inserter, and pressing 'V' to visualize it.

```
0eNrFWd2OqzYQfpWVpd604Sg2f9lcVuoT9LJaIUKcxDpgI2O2TVc8QB+kL9Yn6UA2hIABm83uudmNsfk8zDffzBje0C4taS4ZV2j7hlgieIG2f7yhgh15nNbX1DmnaIuYohlaIR5n9SiWTJ0yqljiJCLbMR4rIVG1Qozv6V9oi6vVLEahBKfOoZQ8TmjnXlK9rBDliilGL8Y0g3PEy2xHJYC3EErGvMiFVM6Opgqgc1HAbYLXmwKU4wff/BU6wy/sbb75sMmeSZpclni1kT1s0mKXYI08SgH/R9H9Pvr1QXleKqSBd1v42tMq5qrrP80O3oT9YCugKCnSaEdP8SsDCLjvwFJFpRGNDQW16xN4TIgAvLZikEnBHSFHEIgBQiLynMpxDNfUijyN1QiGZ2QHTGrv9quX5jrnF7cXNQau/0i670Yng5EHK5lMSqaaIelEQD3GHoBVmrDwZoSlCQx3NCwCfVjckCOY3rP2YQ5MFiq6xiPawrMXtF4SDZz2yqQq4cotgJoVDo2TU+0+AWTGFyuQA6tEqUAItjjViMOPklLedzkOG4LICCPuiMf9dus9TRgofdrd3sZWhe+wWl+bq/LKSbNJlseysW+L/vvn3wn3jsLl56iJ8OggRRZdstT2EKcFrcyDPLwPctwP8mlCwmmJENyf1/MXtI+X0T0rM4emYLoE2eQipToGB5WAU3Y87UTZpEqMXzS7hJZR4n9hlPTT3jVU/A+ESh/zIfHi9+NlKjx8M/o3lnXUc6f6gA/X0X75+HAVfUAR7dTQF5uESjR86Sh4XtaFBSZdWF1/l4CHRuDYNnd0u7BgmDsCXerAizvJQFPQ33m/qFjXWGJ36XZht3Gd2ODWo1yE4TBeUAk/ZhwWGvYn15jLxJ5G4hB1eglsnmyaer+60+5VioOC2E4RnRbbWVcvtHbe06ZPbUz4ViS5RjExetbAtxp5iAs1yReZ2IpY8+XeMoik8T46xdBM1hhgIXCiZEnNGSXELB/hW7H+U4BN3ElOtJhz7CU6F1eylT6HeoYmb2w0RR6rqYdytB6U7RHPEFfjmhm9vlfXD8kV7BGvVErotiLoF5Lv0Ar9Te+715aW55F3FBpScEuJjmCytj7Y1e3JDXPRUc70PPB+yrs7ZXRPcD/ZHjEsmsJ+nz/dFeLNwmMCwfYEhJ9NwH2XPWDBX8pCF7daLt7+ga6fgMkkVcNUsFrS4BNiT1xwT9x8h/8AHTk76Bu/a3l0enL6+RPlhIM+aZ6NvoZqnEYbZc21Z837Aaxp+Vrf0/XLZ2Y/17ReDjOf1XF6WG7niJ3ebZR4+zeYnv/VxFOaTqRdx18q16V5l1gxSWaYcg2Z8u2Zcr+WqZn6uFinS3nylze39xxtphn2Z7RqynCw7OWJb/R9LFz6nsHXfCADRzYUbTufIVcojQEOrv2eAer56VfBnsjTb+/vaGAojnEqBCyEhr64HFE3EJnPJNwEz2t37VXV/4kztn4=
```

Error shown:
```
The mod Circuit Visualizer (0.0.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event circuit_visualizer::cv_visualize_network (ID 185)
__circuit_visualizer__/control.lua:69: attempt to index a nil value
stack traceback:
	__circuit_visualizer__/control.lua:69: in function 'get_connected_networks'
	__circuit_visualizer__/control.lua:411: in function 'on_visualize_network'
	__circuit_visualizer__/control.lua:647: in function <__circuit_visualizer__/control.lua:641>
```

May do a PR if I figure out what's wrong but I've got some mods of my own to finish first.
I'd assume it has something to do with the fact the item can't be connected to a network if it's not actually there, but there is SOME data to attach it to a network should the item actually be placed. I'd have to look into the APIs for circuit networks to know exactly why this is though.

**Comment by GeorgeBroughton** [comment]
line `59` to `61` in `control.lua`

```lua
local function is_entity_valid(entity)
    return entity and entity.valid and entity.unit_number and entity.type ~= "entity-ghost"
end
```
Should return false if the entity is in-fact a ghost entity?

I'm not familiar with lua, but I've got the reference in front of me, and am experienced in other languages.

Presumably code that calls this function should be halting or returning some kind of prompt to the user saying the entity is not valid.

Considering the nature of how i got the error, it's likely this function isn't called somewhere it needs to be. Considering the rest of this mod works, it's likely that it's missing from some code that needs it, rather than has an incorrect operator typo in an if/case statement.

I'll check the functions in the stack trace and see if i can get anywhere with this.

**Comment by M10241024** [comment]
You are correct, this is the error, I will try to fix it right now.

**Comment by M10241024** [comment]
Fixed, thanks for the report.
